#cloud-config

apt_update: true
apt_upgrade: true

groups:
  - microk8s

users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: microk8s

byobu_default: system

snap:
    commands:
        - snap install microk8s --classic --channel=${microk8s_channel}

runcmd:
  - mkdir /home/ubuntu/.kube
  - chown -f -R $USER /home/ubuntu/.kube
  # ubuntu should have been added to group microk8s but to be certain...
  - sudo usermod -a -G microk8s ubuntu
  - echo "Waiting for microk8s to finish..."
  - microk8s status --wait-ready
  - echo "microk8s is now finished!"
  
final_message: "The system is finally up, after $UPTIME seconds"